name: CI

on:
  push:            # runs on pushes to any branch
  pull_request:    # optional, also run on PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Docker image
        run: |
          docker build -t myapp-ci -f Dockerfile .

      - name: Run tests inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/app" \
            -w /app \
            myapp-ci \
            bash -c "pytest --cov=common --cov-report=xml --cov-report=term-missing"

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true

