name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/**/*') }}

      - name: Set up Docker Compose
        run: |
          # Ensure docker-compose CLI is available
          docker compose version

      - name: Build with Docker Compose
        run: |
          docker compose build --pull app

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run tests via Docker Compose
        run: |
          docker compose run --rm \
            -v "${{ github.workspace }}/reports:/reports" \
            app \
            bash -lc "pytest \
              --cov=common \
              --cov-report=xml:/reports/coverage.xml \
              --cov-report=term-missing"

      - name: Upload coverage-report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: reports/coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: reports/coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
